name: Deploy React App to S3

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Sync files to S3
        run: |
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.html" --content-type "text/html"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.css" --content-type "text/css"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.js" --content-type "application/javascript"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.json" --content-type "application/json"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.png" --content-type "image/png"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.jpg" --content-type "image/jpeg"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.svg" --content-type "image/svg+xml"
          aws s3 sync dist/ s3://hiram-bucket/ --exclude "*" --include "*.woff2" --content-type "font/woff2"
